import {
  Trophy,
  Users,
  ScrollText,
  Palmtree,
  Car,
  Rocket,
  MessageCircle,
  Bell,
  User,
  Key,
  Compass,
  Home,
  RefreshCw,
  ClipboardList,
  BarChart3,
  Settings,
  Target,
  Lock,
  Globe,
  Flag,
} from 'lucide-react'

export const icons = {
  trophy: Trophy,
  people: Users,
  scroll: ScrollText,
  palmtree: Palmtree,
  car: Car,
  rocket: Rocket,
  chat: MessageCircle,
  bell: Bell,
  user: User,
  key: Key,
  compass: Compass,
  home: Home,
  tradePortal: RefreshCw,
  draftLog: ClipboardList,
  analytics: BarChart3,
  settings: Settings,
  customScoring: Target,
  lock: Lock,
  globe: Globe,
  flag: Flag,
}